<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.example.spring.lse.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="AuditWSImplService" targetNamespace="http://ws.example.spring.lse.com/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.example.spring.lse.com/" elementFormDefault="unqualified" targetNamespace="http://ws.example.spring.lse.com/" version="1.0">
            <xs:element name="audit" type="tns:audit"/>
            <xs:element name="auditResponse" type="tns:auditResponse"/>
            <xs:complexType name="audit">
                <xs:sequence>
                    <xs:element minOccurs="0" name="message" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="auditResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="auditResponse">
        <wsdl:part element="tns:auditResponse" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="audit">
        <wsdl:part element="tns:audit" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="AuditWS">
        <wsdl:operation name="audit">
            <wsdl:input message="tns:audit" name="audit"></wsdl:input>
            <wsdl:output message="tns:auditResponse" name="auditResponse"></wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AuditWSImplServiceSoapBinding" type="tns:AuditWS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="audit">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="audit">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="auditResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AuditWSImplService">
        <wsdl:port binding="tns:AuditWSImplServiceSoapBinding" name="AuditWSImplPort">
            <soap:address location="http://localhost:8080/jaxws/auditWS"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>